spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MariaDBDialect
  profiles:
    include: db,apiKeys,email,upload
  thymeleaf:
    cache: false
  security:
    user:
      name : user1
      password : 1234
      roles : USER
